[package]
name = "wasm-eval-tgt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The Wasmer API
wasmer = "3.0"
wasmer-compiler-cranelift = "3.1.1"
wasmer-wasi = "3.1.1"
